### PR TITLE
v0.1.0

### PR DESCRIPTION
**Pull request by saimonmoore**
💉 💉 💉

### CODE REVIEW

**Comment by saimonmoore** [comment]
@enricostano @sauloperez my commits are verified even. Merge o ke ase? ;)

**Comment by sauloperez** [comment]
LOL what's going on here :joy:

**Comment by enricostano** [comment]
LOOOOL :muscle:

**Comment by saimonmoore** [comment]
ja ja... At last v0.1.0!

Siringa alive and kicking!

**Comment by saimonmoore** [comment]
@enricostano publish v0.1.0 o ke ase? (If you're busy and you give me access I can publish it ;) )

**Pull request merged**
